# docker-compose.yml
version: "3"

services:
  redis:
    image: "redis:5.0.8"
    ports:
      - "6379:6379"
  frontend:
    image: "node:12.15.0"
    user: "node"
    environment:
      NODE_ENV: "development"
      # REACT_APP_GATEWAY_HOST: "backend-gateway"
      # REACT_APP_GATEWAY_HTTP_PORT: "5000"
      # REACT_APP_GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/frontend/
    volumes:
      - .:/home/node/app/
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run build"
  backend-fileServer:
    image: "node:12.15.0"
    ports:
      - "4000:4000"
      - "4443:4443"
    environment:
      NODE_ENV: "development"
      GATEWAY_HOST: "backend-gateway"
      GATEWAY_HTTP_PORT: "5000"
      GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/backend/fileServer/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
  backend-api:
    image: "node:12.15.0"
    ports:
      - "6000:6000"
      - "6443:6443"
    depends_on:
      - redis
    environment:
      NODE_ENV: "development"
      REDIS_HOST: "redis"
      GATEWAY_HOST: "backend-gateway"
      GATEWAY_HTTP_PORT: "5000"
      GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/backend/api/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
  backend-gateway:
    image: "node:12.15.0"
    ports:
      - "5000:5000"
      - "5443:5443"
    depends_on:
      - backend-api
      - backend-fileServer
    environment:
      NODE_ENV: "development"
      API_HOST: "backend-api"
      API_HTTP_PORT: "6000"
      API_HTTPS_PORT: "6443"
      FILESERVER_HOST: "backend-fileServer"
      FILESERVER_HTTP_PORT: "4000"
      FILESERVER_HTTPS_PORT: "4443"
    working_dir: /home/node/app/backend/gateway/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
